name: Backend CI

on:
  push:
    branches: [v2]
  pull_request:
    branches: [v2]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/backend

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: aurora
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          DATABASE_URL: postgres://root:password@postgres/aurora
